# Generated by Django 5.2.4 on 2025-07-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
